import { NextResponse } from 'next/server';
import { generateWithFallback } from '@/lib/geminiFallback';
import connectDB from '@/lib/mongoose';
import User from '@/models/User';
import LearningPath from '@/models/LearningPath';
import Milestone from '@/models/Milestone';

export async function POST(req) {
  try {
    const data = await req.json();
    const { userId, interests, experience, goals } = data; // Note: We now require userId from frontend

    if (!userId) {
      return NextResponse.json({ error: "User must be logged in to onboard." }, { status: 401 });
    }

    // AI Generation
    const prompt = `
      You are an expert AI learning path generator. Based on the following user profile:
      - Interests: ${interests}
      - Experience Level: ${experience}
      - Ultimate Goal: ${goals}
      
      Generate a structured learning roadmap. Return ONLY a valid JSON array of milestone objects.
      Each object must have exactly these keys:
      - "title": (String)
      - "type": (String, either "Course" or "Project")
      - "description": (String)
      - "aiNote": (String, explaining why this is recommended based on their specific goal)
      - "resourceUrl": (String, provide a real search link, e.g. "https://www.youtube.com/results?search_query=react+course")
      - "estimatedTime": (String, realistic time e.g. "2 Weeks", "4 Hours")
    `;

    const response = await generateWithFallback(prompt, { responseMimeType: 'application/json' });

    const milestonesRaw = response.text;
    const milestonesList = JSON.parse(milestonesRaw);

    await connectDB();

    // Update User Profile
    await User.findByIdAndUpdate(userId, { interests, experience, goals });

    // Check if path already exists, if so delete it (re-generating)
    const existingPath = await LearningPath.findOne({ user_id: userId });
    if (existingPath) {
      await Milestone.deleteMany({ learning_path_id: existingPath._id });
      await LearningPath.findByIdAndDelete(existingPath._id);
    }

    // Save New Path
    const newPath = await LearningPath.create({
      user_id: userId,
      title: `Path to ${goals}`,
      description: 'Personalized learning roadmap generated by AI.'
    });

    const milestoneDocs = milestonesList.map((m, idx) => ({
      learning_path_id: newPath._id,
      title: m.title,
      type: m.type,
      status: idx === 0 ? 'in-progress' : 'locked',
      description: m.description,
      aiNote: m.aiNote,
      resourceUrl: m.resourceUrl,
      estimatedTime: m.estimatedTime,
      display_order: idx
    }));

    await Milestone.insertMany(milestoneDocs);

    return NextResponse.json({ success: true, pathId: newPath._id.toString(), path: milestonesList });
  } catch (error) {
    console.error("Error generating path:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
